## Data Processing in Machine Learning

Data Processing is a task of converting data from a given form to a much more usable and desired form i.e. making it more meaningful and informative to build a machine learning model. Using Machine Learning algorithms, mathematical modelling and statistical knowledge, this entire process can be automated. 

In tis article I have used very simple dataset to walktrhough on different steps in data processing before building a machine learning model.

<b> Prerequisites to undestand this article : Basic Python Knowledge </b>

<b>Reference :</b> I am writing this material from the knowledge i gained from Machine Learnig A-Z course from <b>Superdatascience.com</b>

### Importing libraries

#Libraries - A library is a tool that you can use to make a speciic job by giving some inputs to the
functions in the library to get necessary outcome. 

Three essential libraries for machine learnig are

1. Numpy - used for statisctical and mathematical operations
2. matplotlib.pyplot -used for graphics
3. Pandas - used to import and manage datasets

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### 1.Importing dataset

In [43]:
#importing dataset
dataset = pd.read_csv('Data.csv')
dataset


Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

### 2. Find independent and dependent variable

#Independent variables (also referred to as Features) are the input for a process that is being analyzes.
#Dependent variables are the output of the process.

In [23]:
#Independent Variables
X = dataset.iloc[:,:-1].values #:-- retrieves all the columns , :-1 -> retrieves all the columnhs except last one

In [47]:
X # shows the matrix of indpendent variables

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [25]:
#Dependent variable
y = dataset.iloc[:,3].values 

In [49]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

### 3. Missing Data

#missing data - it is dangerous to remove rows of data which is having missing values. 
A row with missing value may have very useful observation from other column values. Below are the methods to handle missing data.

1. Replace missing value with the mean of values in the column that contain missing data


In [21]:
#1. Replace missing value with the mean of values in the column that contain missing data

In [28]:
from sklearn.preprocessing import Imputer # this library contains lot of classes and methods to preprocess any dataset

In [35]:
imputer = Imputer(missing_values='NaN',strategy='mean',axis=0) # mean is the default value for strategy
imputer = imputer.fit(X[:,1:3])

In [38]:
X[:,1:3] = imputer.transform(X[:,1:3]) # this method replaces the missing values with mean. 

In [ ]:
#you can also use "median" or "most_frequent" methods for replacement

In [46]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

### 4. Categorical Data

Categorical variables represent types of data which may be divided into groups.

In our dataset we have two categorical varialbes "Country" and "Purchased"

1. Country - France, Spain and Germany (Total 3 categories)
2. Purchased - Yes , No (Total 2 categories)

Categorical variables need to be encoded to numbers to perform mathematical operations / calculations in Machine learning

In [58]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
#Country values before transformation or encoding using LabelEncoder
X[:,0]

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0], dtype=object)

In [59]:
labelencoder_X = LabelEncoder()
X[:,0] = labelencoder_X.fit_transform(X[:,0])

In [60]:
#Country values after transformation or encoding using LabelEncoder
X[:,0] 

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0], dtype=object)

#<b>Note</b> : Above encoding may lead to number comparison or ordering during the machine learning process.
To avoid such issues we should introduce additional columns or dummy varialbes  to represent each category
To create dummy variables we need to use another class <b>OneHotEncoder</b> which i have included in the import function above

If you are not clear about Dummy variables, I will explaining more in detail when i post an article about Multiple linear regression.

In [61]:
onehotencoder = OneHotEncoder(categorical_features=[0])
X = onehotencoder.fit_transform(X).toarray()

D:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [71]:
print(X)

[[1.00000000e+00 0.00000000e+00 0.00000000e+00 4.40000000e+01
  7.20000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 2.70000000e+01
  4.80000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 3.00000000e+01
  5.40000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.80000000e+01
  6.10000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 4.00000000e+01
  6.37777778e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.50000000e+01
  5.80000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.87777778e+01
  5.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.80000000e+01
  7.90000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 5.00000000e+01
  8.30000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.70000000e+01
  6.70000000e+04]]


In [65]:
# Create label encoder for second categorical variable

In [66]:
labelencoder_y = LabelEncoder()
y= labelencoder_y.fit_transform(y)

In [68]:
y # after label encoding

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

### 5. Splitting data into Training set and Test set 

In any machine learnig model, we need to split the data set into Training and Test sets.
Reason is the Model which we build learns from the dataset we provide with different correlations.
Predictions needs to be evaluated with new or test data sets to ensure the model works for any new data set.
This process is iterated by feeding different datasets to the model to make accurate predictions.

In practice while working preparing data for machine learning models, we should always split the dataset into Trainig and Test sets.

In [73]:
from sklearn.model_selection import train_test_split

In [74]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)
# X train - training part of independent variable
# X test - testing part of independent variable
# y train - training part of dependent variable
# y test - testing part of dependent variable
# X - features of independent variable
# y - feature of dependent variable

In [77]:
# since we chose 20 % for testing, we have 8 observations for training out of 10
X_train.shape, X_test.shape, y_train.shape, y_test.shape  


((8, 5), (2, 5), (8,), (2,))

### 6. Feature Scaling

Feature scaling is a method used to normalize the range of independent variables or features of data. In data processing, it is also known as data normalization and is generally performed during the data preprocessing step.

When you’re working with a learning model, it is important to scale the features to a range which is centered around zero. This is done so that the variance of the features are in the same range. If a feature’s variance is orders of magnitude more than the variance of other features, that particular feature might dominate other features in the dataset, which is not something we want happening in our model.

The aim here is to to achieve Gaussian with zero mean and unit variance. There are many ways of doing this, two most popular are standardisation and normalisation.

In [80]:
from sklearn.preprocessing import StandardScaler

In [85]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
#Note you should always fit before transforming the dataset to build a uniform train and test data set. 
X_test = sc_X.transform(X_test)

In [86]:
X_train

array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]])

In [87]:
X_test

array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]])

Note: feature scaling for dependent variable is not required for this dataset

I will share more techniques in analysing data using matplotlib and seaborn in next article 